### PR TITLE
Append message_bus to the end of the middleware stack.

### PR DESCRIPTION
**Pull request by tgxworld**
fixes https://github.com/SamSaffron/message_bus/issues/24.

### CODE REVIEW

**Comment by SamSaffron** [comment]
nope, its meant to be at a very particular spot, if its too deep in the stack certain middlewares will mess with it.

**Comment by tgxworld** [comment]
@SamSaffron How about inserting after whatever `Rails.application.config.session_store` is? I think that is way more flexible than assuming the flash middleware is present.

**Comment by SamSaffron** [comment]
That could work, (except for people who disable sessions)

**Comment by tgxworld** [comment]
I think that needs to  be a check that `Rails.application.config.session_store` exists too and raise a message [when it isn't](https://github.com/rails/rails/blob/master/railties/lib/rails/application/default_middleware_stack.rb#L47) since the flash middleware will not be inserted.

**Comment by tgxworld** [comment]
@SamSaffron  I think the follow improves it. Not sure if that was what you had in mind.

```ruby
  initializer "message_bus.configure_init", after: :load_config_initializers do |app|
    MessageBus::MessageHandler.load_handlers("#{Rails.root}/app/message_handlers")

    # We want MessageBus to show up after the session middleware.
    if session_store = app.config.session_store
      app.middleware.insert_after(session_store, MessageBus::Rack::Middleware)
    end

    MessageBus.logger = Rails.logger
  end
```

**Pull request closed without merging**
