### PR TITLE
FIX: Publish status update to all subscribed clients when a message i…

### PR DESCRIPTION
**Pull request by tgxworld**
…s filtered.

### CODE REVIEW

**Comment by tgxworld** [comment]
Spec failures does not seem to be related

**Comment by SamSaffron** [comment]
this looks good! awesome

**Comment by benlangfeld** [comment]
What's the purpose of this change? I'm not sure I understand what it achieves.

**Comment by SamSaffron** [comment]
This stops situation where a client keeps asking for messages they clearly have no access to forcing the server to a whole bunch of work on every single call.

**Pull request merged**
