### PR TITLE
Rescue from Errno::EPIPE when sending a message

### PR DESCRIPTION
**Pull request by cannikin**
For issue #146

### CODE REVIEW

**Comment by SamSaffron** [comment]
@jeremyevans  I am a tiny bit mixed on this, agree that eating the error is probably best, what do you think?

**Comment by jeremyevans** [comment]
I agree that removing disconnected clients should probably not raise errors, but handling just EPIPE seems questionable (though it may work fine for puma).  Maybe rescuing IOError and SystemCallError?

**Comment by SamSaffron** [comment]
Yeah, a wider net sounds like a good idea

**Comment by cannikin** [comment]
Updated! Do you guys still like the spec that's there or should I try to raise anything else to verify it'll get caught?

**Comment by SamSaffron** [comment]
I think this is fine, let's try it out.

**Pull request merged**
