### PR TITLE
Deprecated methods and rubocop

### PR DESCRIPTION
**Pull request by lis2**
Housekeeping, deprecated Minitest methods and Rubocop magic comment

### CODE REVIEW

**Comment by jeremyevans** [comment]
Alternatively, if we don't want to uglify the specs, we could use `minitest-global_expectations` and we would only need to change a couple lines.

**Comment by SamSaffron** [comment]
I am with Jeremy here @lis2, lets just pull in mini-test-global_expectations 

This new pattern does make the spec suite quite ugly.

**Comment by lis2** [comment]
@jeremyevans @SamSaffron fair point :) fixed

**Comment by SamSaffron** [comment]
Looks great now! thanks!

**Pull request merged**
